shunya_home: /opt/shunya

spring:
  application:
    name: dialog

spring.main.web-application-type: reactive

logging:
  level:
    com.shunya: INFO
    org.springframework: DEBUG
    com.netflix.discovery: ERROR
  file:
    path: ${shunya_home}/logs
    name: ${logging.file.path}/${spring.application.name}.log
    max-history: 7
    max-size: 20MB
  pattern:
      rolling-file-name: ${LOG_FILE}.%d{yyyy-MM}.%i.gz